Адаптивная версия главной
khorosh/airbnb-demo-frontend pull request #1
Opened 2017-11-12 06:52 UTC by khorosh

2017-11-12 13:40 UTC, imevro requested changes

2017-11-12 13:40 UTC, evgenyrodionov commented on src/Explore/Styled.js
> +export const Card = styled.div`
ссылка же

2017-11-12 13:40 UTC, evgenyrodionov commented on src/UI.js
> +    left: 98%;
не проще ли right?

2017-11-12 17:44 UTC, khorosh commented
1. Перевёл карточки из div в ссылки. 
2. Упростил позиционирование стрелки у карусели.

2017-11-13 11:15 UTC, merged

2017-11-13 11:15 UTC, evgenyrodionov commented
Сделай пулл в мастере